# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='largegenre',
            unique_together=set([('prefecture', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='middlegenre',
            unique_together=set([('prefecture', 'large_genre', 'name')]),
        ),
    ]
