# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170722_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='middle_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='project.MiddleGenre'),
        ),
    ]
