# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20170722_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='', upload_to=project.models.Topic.get_image_path),
        ),
        migrations.AlterField(
            model_name='topic',
            name='tag_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
