# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170722_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Prefecture')),
            ],
        ),
    ]
