# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='largegenre',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='middlegenre',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='largegenre',
            name='prefecture',
        ),
        migrations.RemoveField(
            model_name='middlegenre',
            name='prefecture',
        ),
    ]
