# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20170729_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='largegenre',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='project.City'),
        ),
        migrations.AddField(
            model_name='middlegenre',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='project.City'),
        ),
        migrations.AlterUniqueTogether(
            name='largegenre',
            unique_together=set([('city', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='middlegenre',
            unique_together=set([('large_genre', 'name')]),
        ),
    ]
