# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20170729_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='middlegenre',
            name='city',
        ),
    ]
