# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_middlegenre_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largegenre',
            name='city',
            field=models.ForeignKey(default='13', on_delete=django.db.models.deletion.CASCADE, to='project.City'),
        ),
    ]
