# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20170729_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.MiddleGenre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('user', 'middle_genre')]),
        ),
    ]
